export const IrishAurals = [
  {
    year: "2019",
    link: "https://www.examinations.ie/archive/exampapers/2019/LC001ZLP017IV.mp3",
  },
  {
    year: "2018",
    link: "https://www.examinations.ie/archive/exampapers/2018/LC001ZLP017IV.mp3",
  },
  {
    year: "2017",
    link: "https://www.examinations.ie/archive/exampapers/2017/LC001ZLP017IV.mp3",
  },
  {
    year: "2016",
    link: "https://www.examinations.ie/archive/exampapers/2016/LC001ZLP017IV.mp3",
  },
  {
    year: "2015",
    link: "https://www.examinations.ie/archive/exampapers/2015/LC001ZLP017IV.mp3",
  },
  {
    year: "2014",
    link: "https://www.examinations.ie/archive/exampapers/2014/LC001ZLP017IV.mp3",
  },
  {
    year: "2013",
    link: "https://www.examinations.ie/archive/exampapers/2013/LC001ZLP017IV.mp3",
  },
  {
    year: "2012",
    link: "https://www.examinations.ie/archive/exampapers/2012/LC001ZLPO17IV.mp3",
  },
  {
    year: "2011",
    link: "https://www.examinations.ie/archive/exampapers/2011/LC001ZLP017IV.mp3",
  },
  {
    year: "2010",
    link: "https://www.examinations.ie/archive/exampapers/2010/LC001ZLP017IV.mp3",
  },
  {
    year: "2009",
    link: "https://www.examinations.ie/archive/exampapers/2009/LC001ZLP017IV.mp3",
  },
  {
    year: "2008",
    link: "https://www.examinations.ie/archive/exampapers/2008/LC001ZLPO17IV.mp3",
  },
  {
    year: "2007",
    link: "https://www.examinations.ie/archive/exampapers/2007/LC001ZLP00IV.mp3",
  },
  {
    year: "2006",
    link: "https://drive.google.com/open?id=1yRkjjeqKsXFNdib2gz1PlcZYzWBgifdZ",
  },
];
export const HLMathsPapers = [
  {
    tipe: "ExamPaper",
    year: "2019",
    paper: "One",
    link: "https://drive.google.com/open?id=1OKE3hwhuJCAZsHUL8M0sw00YHyM9Fz39",
  },
  {
    tipe: "ExamPaper",
    year: "2019",
    paper: "Two",
    link: "https://drive.google.com/open?id=11tPHhko7Zju4U30SQSIApgjWNn8Mix6J",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    paper: "One",
    link: "https://drive.google.com/open?id=1qJQwEBLZdhHfAR0gncERUMuxs-ZQV9F1",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    paper: "Two",
    link: "https://drive.google.com/open?id=1GXnSnpwFUSXy_BOi3xjcdVuhH6xAaHRi",
  },
  {
    tipe: "ExamPaper",
    year: "2017",
    paper: "One",
    link: "https://drive.google.com/open?id=1KcClmGcQouyvIXKyIGow12h-LOK4aZik",
  },
  {
    tipe: "ExamPaper",
    year: "2017",
    paper: "Two",
    link: "https://drive.google.com/open?id=1ilwLBgKbHUljVsajTLSVebpb0z6Qyg6z",
  },
  {
    tipe: "ExamPaper",
    year: "2016",
    paper: "One",
    link: "https://drive.google.com/open?id=1eljAD5CpIZlLTgiB9BRFc2-WbBrj_Vow",
  },
  {
    tipe: "ExamPaper",
    year: "2016",
    paper: "Two",
    link: "https://drive.google.com/open?id=1pWtUhMvKS8_rf086QzGm5ocvfjn54SLG",
  },
  {
    tipe: "ExamPaper",
    year: "2015",
    paper: "One",
    link: "https://drive.google.com/open?id=1AS8DnAszP3Kp2FI4-Rxe5f5XQHFKjFMn",
  },
  {
    tipe: "ExamPaper",
    year: "2015",
    paper: "Two",
    link: "https://drive.google.com/open?id=1WVcsRYhrn3fkUNBL8bWERgdEcVaioBHq",
  },
  {
    tipe: "ExamPaper",
    year: "2014",
    paper: "One",
    link: "https://drive.google.com/open?id=1ryiYG4Dn_Eg4xFwb9Adi8_gDXFIeccpY",
  },
  {
    tipe: "ExamPaper",
    year: "2014",
    paper: "Two",
    link: "https://drive.google.com/open?id=1R08nZ4e86h6K2AnlksYzJvCdqkvPv7o_",
  },
  {
    tipe: "ExamPaper",
    year: "2013",
    paper: "One",
    link: "https://drive.google.com/open?id=1ggdENITr5VjwtwTB1SM6Ee_V0WWXajAG",
  },
  {
    tipe: "ExamPaper",
    year: "2013",
    paper: "Two",
    link: "https://drive.google.com/open?id=1hJiCSkhOdaq9SlKovlN0lHTo_wJ7tjHT",
  },
  {
    tipe: "ExamPaper",
    year: "2012",
    paper: "One",
    link: "https://drive.google.com/open?id=1yLHZzdY2fvAmMqTgxn90QEgU559xThX-",
  },
  {
    tipe: "ExamPaper",
    year: "2012",
    paper: "Two",
    link: "https://drive.google.com/open?id=1u4vrRgO8iGuR7rTZDC-kuwAeEIYmedqB",
  },
  {
    tipe: "ExamPaper",
    year: "2011",
    paper: "One",
    link: "https://drive.google.com/open?id=1EcI3cJkjsqZXxCBDjOhoabfu_YDwv6_7",
  },
  {
    tipe: "ExamPaper",
    year: "2011",
    paper: "Two",
    link: "https://drive.google.com/open?id=1f_GnH-KrFLTmygjwecf5jYxlVzN4mViN",
  },
  {
    tipe: "ExamPaper",
    year: "2010",
    paper: "One",
    link: "https://drive.google.com/open?id=1vNvDq1kRJMFuxica59FTxlOM5vRSMtQc",
  },
  {
    tipe: "ExamPaper",
    year: "2010",
    paper: "Two",
    link: "https://drive.google.com/open?id=10lqz-Ch40B4HUcsGIy9bXjtlsy7jUg0A",
  },
  {
    tipe: "ExamPaper",
    year: "2009",
    paper: "One",
    link: "https://drive.google.com/open?id=13RwygqounJiRp9KlqYIN8hYY2b8Mmj_a",
  },
  {
    tipe: "ExamPaper",
    year: "2009",
    paper: "Two",
    link: "https://drive.google.com/open?id=17hWCR0oz1LbkxCASdOIduj29_5pxNhEY",
  },
  {
    tipe: "ExamPaper",
    year: "2008",
    paper: "One",
    link: "https://drive.google.com/open?id=1gADmICMI9voe3Yxdhix3n-X-m9Xeb0Je",
  },
  {
    tipe: "ExamPaper",
    year: "2008",
    paper: "Two",
    link: "https://drive.google.com/open?id=1i-frtVcqBB0nf176JqsL03zL0NzfrMQs",
  },
  {
    tipe: "ExamPaper",
    year: "2007",
    paper: "One",
    link: "https://drive.google.com/open?id=1EGZSM2f5YjUgvaEbnqz0zj0k_dwMqb9j",
  },
  {
    tipe: "ExamPaper",
    year: "2007",
    paper: "Two",
    link: "https://drive.google.com/open?id=1c4pIr34s89oaBVxWrcV0sHrTbLe3qMvY",
  },
  {
    tipe: "ExamPaper",
    year: "2006",
    paper: "One",
    link: "https://drive.google.com/open?id=1Vv7--ek-nYPJSPLXEVsRapwzKGGoy5-r",
  },
  {
    tipe: "ExamPaper",
    year: "2006",
    paper: "Two",
    link: "https://drive.google.com/open?id=10avQcRp3lPflYYn1TNpUfiC4IVlJGXv9",
  },
  {
    tipe: "ExamPaper",
    year: "2005",
    paper: "One",
    link: "https://drive.google.com/open?id=1ZGAjNLCd1HcgKbPfrN_jm38LVqGm45Ai",
  },
  {
    tipe: "ExamPaper",
    year: "2005",
    paper: "Two",
    link: "https://drive.google.com/open?id=17LtXXHr-1onraeUrnw_P2UdB8pgQVhi2",
  },
  {
    tipe: "ExamPaper",
    year: "2004",
    paper: "One",
    link: "https://drive.google.com/open?id=1rp-QVJmkDTqoOGtLtaXTVmK5ZSpOvz2h",
  },
  {
    tipe: "ExamPaper",
    year: "2004",
    paper: "Two",
    link: "https://drive.google.com/open?id=1P9e4Jj7K8M0DZACIEQLKDTMXjoy-q_Zl",
  },
  {
    tipe: "ExamPaper",
    year: "2003",
    paper: "One",
    link: "https://drive.google.com/open?id=1k1jDqvt2-fgpu1wEEHlQXQ6TOV50NiCn",
  },
  {
    tipe: "ExamPaper",
    year: "2003",
    paper: "Two",
    link: "https://drive.google.com/open?id=1I8lu9F16ZKwrP0u0DANcZWuQ4Byr5yUo",
  },
  {
    tipe: "ExamPaper",
    year: "2002",
    paper: "One",
    link: "https://drive.google.com/open?id=1mVSZGBpcA1GxPi2479lNz-1lRu7eltSV",
  },
  {
    tipe: "ExamPaper",
    year: "2002",
    paper: "Two",
    link: "https://drive.google.com/open?id=1uV0BqsOH6K9YsSV286eNBI902jQ0rXGD",
  },
  {
    tipe: "ExamPaper",
    year: "2001",
    paper: "One",
    link: "https://drive.google.com/open?id=1grdZNqtziqUy0rXKcweP7valH21L5S4X",
  },
  {
    tipe: "ExamPaper",
    year: "2001",
    paper: "Two",
    link: "https://drive.google.com/open?id=1lrg-pBWucReOew73QGzTpI5tiGMni-LU",
  },
  {
    tipe: "ExamPaper",
    year: "2000",
    paper: "One",
    link: "https://drive.google.com/open?id=1jssR1kXDWCgPPUyotRG73Zxoo86bBc8y",
  },
  {
    tipe: "MarkingScheme",
    year: "2019",
    paper: "",
    link: "https://drive.google.com/open?id=1p_ARszktKYOhC4Q2IaLn-q4l7GjhK94k",
  },
  {
    tipe: "MarkingScheme",
    year: "2018",
    paper: "",
    link: "https://drive.google.com/open?id=1YVaNtFcwvNzrMtJ6e8i1abcHIHr8_uP8",
  },
  {
    tipe: "MarkingScheme",
    year: "2017",
    paper: "",
    link: "https://drive.google.com/open?id=1vnzKZf89e1uIwGMVeoipQ3PRavnhylWV",
  },
  {
    tipe: "MarkingScheme",
    year: "2016",
    paper: "",
    link: "https://drive.google.com/open?id=1nqv0sv8oUDlFJ9kCv78nHNKftq3LgPC1",
  },
  {
    tipe: "MarkingScheme",
    year: "2015",
    paper: "",
    link: "https://drive.google.com/open?id=1C8w80o1gIc2c1Wa6OkErd_K6xA8J6k9e",
  },
  {
    tipe: "MarkingScheme",
    year: "2014",
    paper: "",
    link: "https://drive.google.com/open?id=1lYZjktbOPiMWtTCxMqxJVLrT6UAkIvH0",
  },
  {
    tipe: "MarkingScheme",
    year: "2013",
    paper: "",
    link: "https://drive.google.com/open?id=1PPrtQYSXDL8PXbs7cZqEPudDlwstLu7T",
  },
  {
    tipe: "MarkingScheme",
    year: "2012",
    paper: "",
    link: "https://drive.google.com/open?id=15QOr4GhZMDdNy783ZKvrZzY-Qirc678p",
  },
  {
    tipe: "MarkingScheme",
    year: "2011",
    paper: "",
    link: "https://drive.google.com/open?id=1lqkSNcgCH3LW7_OIcAX5CNLpP8VR6jop",
  },
  {
    tipe: "MarkingScheme",
    year: "2010",
    paper: "",
    link: "https://drive.google.com/open?id=1bHve1w4EtG5r3-NSqkXqHTyXTE4dmiRT",
  },
  {
    tipe: "MarkingScheme",
    year: "2009",
    paper: "",
    link: "https://drive.google.com/open?id=1LZf6vaPwA7gENC9jFmVkW0Wa2LcIFcX1",
  },
  {
    tipe: "MarkingScheme",
    year: "2008",
    paper: "",
    link: "https://drive.google.com/open?id=1AJzWDteZ_6_InIxh8OvbRPYgw478mWy0",
  },
  {
    tipe: "MarkingScheme",
    year: "2007",
    paper: "",
    link: "https://drive.google.com/open?id=1cwhO_gFzHRhD_F6FAO8dQyoRBSYi2IOu",
  },
  {
    tipe: "MarkingScheme",
    year: "2006",
    paper: "",
    link: "https://drive.google.com/open?id=1n3Vv93xtyfFbO02aLRX2gpFICgvTU_cR",
  },
  {
    tipe: "MarkingScheme",
    year: "2005",
    paper: "",
    link: "https://drive.google.com/open?id=1GOlZmIBJHhqUfSM5H47-MmRdRSyldpHe",
  },
  {
    tipe: "MarkingScheme",
    year: "2004",
    paper: "",
    link: "https://drive.google.com/open?id=1MKImss2BE3mgArW0dOoKBaSNBQswiujs",
  },
  {
    tipe: "MarkingScheme",
    year: "2003",
    paper: "",
    link: "https://drive.google.com/open?id=1x3KkT9StyamE-k4vFr2RIV37iP1mQJbp",
  },
  {
    tipe: "MarkingScheme",
    year: "2002",
    paper: "",
    link: "https://drive.google.com/open?id=1KIg4EL2iSBL6qmGfYggZUzR7Gf1SnceW",
  },
  {
    tipe: "MarkingScheme",
    year: "2001",
    paper: "",
    link: "https://drive.google.com/open?id=1UlNcocsJNVJ0Exy_5HlhcDTJXOdPARWj",
  },
];
export const HLEnglishPapers = [
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2019",
    link: "https://drive.google.com/open?id=1Bg2ya2Mky9wuZwMhTopwS5N0H4pNo3JY",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2019",
    link: "https://drive.google.com/open?id=1DWyS4nMWO721qq8us9iyeV4m5bZAcs8V",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2018",
    link: "https://drive.google.com/open?id=1fcLMJSEbq5WiynDPhqlwcfwyYpAwWFKb",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2018",
    link: "https://drive.google.com/open?id=1HDmG49fmUKx7ummK0MQweATzVLOYfxQo",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2017",
    link: "https://drive.google.com/open?id=1U-rpGcBV--dCS4MplF5_3dwT6lrs9ccW",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2017",
    link: "https://drive.google.com/open?id=1RJhDW_gG_sSDWFMEkyFEgrYWwsrcRVMk",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2016",
    link: "https://drive.google.com/open?id=1rR7Woga_GnytwIC4jR39iIstzj_TOLFo",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2016",
    link: "https://drive.google.com/open?id=1Qpys_gOT0oHGAB1wZ4A1k5CXBwPFcetw",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2015",
    link: "https://drive.google.com/open?id=1i-WXqHMo33dmdJgypcc-DwnLc1gnC7sb",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2015",
    link: "https://drive.google.com/open?id=1r7VdlGUNzp016m4po4erIrp52_0sKfeg",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2014",
    link: "https://drive.google.com/open?id=1oYxGzjycXVxkb9pzgpHZITcuKTbSgOCn",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2014",
    link: "https://drive.google.com/open?id=1-zql2FVxxvBG3LTqK64UMjSLfmXYhzQF",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2013",
    link: "https://drive.google.com/open?id=1P2UF6lvi4WfhhXlyXelI9ZS_ipeuac04",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2013",
    link: "https://drive.google.com/open?id=1bmb-xLlWdF6sUN8Ib2YA6Gkx7QFfhgve",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2012",
    link: "https://drive.google.com/open?id=1JtznQFbIZZ_g5BGU1pHK1yX__OlVqN4J",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2012",
    link: "https://drive.google.com/open?id=14uuBBBIw4Pib-FDyPu46FjX4HKP9C_WA",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2011",
    link: "https://drive.google.com/open?id=1t_Jb412gmY-7x_OK8YD1G5WsYAjvIThp",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2011",
    link: "https://drive.google.com/open?id=1sEyzaUU_peCy8qQcWKttGovRIRO4wMhL",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2010",
    link: "https://drive.google.com/open?id=1hBYBlmFXu2IwEbrGFS9fUpKIBtpaDtO_",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2010",
    link: "https://drive.google.com/open?id=1vpW9LiwTFVw_icpkF55yP9lpXBmc5VHg",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2009",
    link: "https://drive.google.com/open?id=1_qezY6Vc1M-0hfvi4qGVxodeOqfzp5sw",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2009",
    link: "https://drive.google.com/open?id=1GBtvdGS7oFNU2FEgysaLCa4pcD1tG38a",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2008",
    link: "https://drive.google.com/open?id=1y2yh-Tp-4Wm8M-exPk37KhmydgXJ0bah",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2008",
    link: "https://drive.google.com/open?id=18U5lKJ-FgFArsbRFy4B9UvZtfuz177uD",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2007",
    link: "https://drive.google.com/open?id=1kG7FgAeRQgQuvbMcMLgo4t1HWViTHX8D",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2007",
    link: "https://drive.google.com/open?id=1U32hter8a-hTfjvMzPOFIq3bQVeAk3uJ",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2006",
    link: "https://drive.google.com/open?id=1IQ8Eea1Twb0Hns3uQgN2Z2dGfog0Z-w0",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2006",
    link: "https://drive.google.com/open?id=1bdwkn5vi7PirI8u_6eZ8j65gdTBzPUxU",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2005",
    link: "https://drive.google.com/open?id=1cg699ErsXrepKyesOP5gUrpLFO8cbUkA",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2005",
    link: "https://drive.google.com/open?id=1FL_IN17hL2iUokiJuNbt8dTsCW9QBQDx",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2004",
    link: "https://drive.google.com/open?id=1U2ZDn9RKcCkeU4fUlMPAQ9GptH738viw",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2004",
    link: "https://drive.google.com/open?id=1t7gXWVPz9frh2AjRKD--MXX9hhLrEl-j",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2003",
    link: "https://drive.google.com/open?id=1tk3ytx-q8w7iIxEv_o5pSedGkbqavUDJ",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2003",
    link: "https://drive.google.com/open?id=1Ei1cmeNYNdJbCsHlkpDEbBYMtPtRczFv",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2002",
    link: "https://drive.google.com/open?id=1hNd2q6xcUpcqXB8deeYDnx8TWy362THv",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2002",
    link: "https://drive.google.com/open?id=1Rxzt-PUeiRUxdliHYlF1eBS1WHgE97jx",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2001",
    link: "https://drive.google.com/open?id=16jlDfI2xfVGjbvV-jBsWAIOULVs5BjT3",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2001",
    link: "https://drive.google.com/open?id=1h1hlp1RjCX48ZQMyXiq671rNMFunqZVW",
  },
  {
    tipe: "MarkingScheme",
    year: "2019",
    link: "https://drive.google.com/open?id=1MEjXgKIY9ZY-QeqwGkdRPSTtqVAa3Kt8",
  },
  {
    tipe: "MarkingScheme",
    year: "2018",
    link: "https://drive.google.com/open?id=1SVySp9e4KOqZsZtsRj7L55FG4iJLkG-s",
  },
  {
    tipe: "MarkingScheme",
    year: "2017",
    link: "https://drive.google.com/open?id=1gsN6sMzFmJdE5GonqPsRhaVg3bpDWP2J",
  },
  {
    tipe: "MarkingScheme",
    year: "2016",
    link: "https://drive.google.com/open?id=1VWGe0oBY_eTCDXPrRlXiiXot6gJZnoen",
  },
  {
    tipe: "MarkingScheme",
    year: "2015",
    link: "https://drive.google.com/open?id=1yQa6EWXHgIU_7hGN5hpHfI1tCwCp8LdC",
  },
  {
    tipe: "MarkingScheme",
    year: "2014",
    link: "https://drive.google.com/open?id=1mWO6XdQKENpzLT7MLOUErvXDfNtrUouH",
  },
  {
    tipe: "MarkingScheme",
    year: "2013",
    link: "https://drive.google.com/open?id=1-OfseaMExU6JtLGaXp7AoH0VjBSDZK4_",
  },
  {
    tipe: "MarkingScheme",
    year: "2012",
    link: "https://drive.google.com/open?id=1TdwiJNt83yqwYUXYIPj5EBvJW3hIfkUK",
  },
  {
    tipe: "MarkingScheme",
    year: "2011",
    link: "https://drive.google.com/open?id=1CIUuvOWBOXsb2QmU54uLx-x5jmK5bmdM",
  },
  {
    tipe: "MarkingScheme",
    year: "2010",
    link: "https://drive.google.com/open?id=1cen5XcjcLygdtuC1B9tXVc1TrhFEBJd1",
  },
  {
    tipe: "MarkingScheme",
    year: "2009",
    link: "https://drive.google.com/open?id=1Qwu2FL_q7Sgq4rzeqEqjc7o3Hoi-4eRR",
  },
  {
    tipe: "MarkingScheme",
    year: "2008",
    link: "https://drive.google.com/open?id=1cBQqYLzxCqJBTT45g4A4nkMglw6Nv0Gh",
  },
  {
    tipe: "MarkingScheme",
    year: "2007",
    link: "https://drive.google.com/open?id=1T-8TXwGbar_aEebcU1JCsOhXRk1sC3e4",
  },
  {
    tipe: "MarkingScheme",
    year: "2006",
    link: "https://drive.google.com/open?id=17kEQzonQDpUXFs6EP6z__YAweXeDHExS",
  },
  {
    tipe: "MarkingScheme",
    year: "2005",
    link: "https://drive.google.com/open?id=1UWaoDdz2uew-z4h2_pTBQl0ByLfPoxKF",
  },
  {
    tipe: "MarkingScheme",
    year: "2004",
    link: "https://drive.google.com/open?id=1pbbqjBFbHOsBaqsc8gOl69cHlVS33iPg",
  },
  {
    tipe: "MarkingScheme",
    year: "2003",
    link: "https://drive.google.com/open?id=1tRr5f7a-9drb9rMf8RgY7TM61LBcKXjG",
  },
  {
    tipe: "MarkingScheme",
    year: "2002",
    link: "https://drive.google.com/open?id=1Rz4Ze-kbWPuwgktv3w-aICTOFsq-J0hW",
  },
  {
    tipe: "MarkingScheme",
    year: "2001",
    link: "https://drive.google.com/open?id=1Ql50bPzqwWjN1raMt-hFv6Y8kQvNsrDO",
  },
];
export const HLIrishPapers = [
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2019",
    link: "https://drive.google.com/open?id=1_DmSN52N1ilR0r_jxgWfWH3SF6OycIs4",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2019",
    link: "https://drive.google.com/open?id=1kiC8s9d9ktqCvZ6sU3hd-iMRGY6xMxCO",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2018",
    link: "https://drive.google.com/open?id=1F9NXEE4IqGimXAIjRxw3samjCrI1bpdo",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2018",
    link: "https://drive.google.com/open?id=1Ywp-M6-Cbxc3XUcTWtoHkD3nERDyX1B6",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2017",
    link: "https://drive.google.com/open?id=1KjvONO332ZYjfCrpDkL7tcVgybLXWe72",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2017",
    link: "https://drive.google.com/open?id=1DLcY_KE3WV-X9e34OH5A6yw9iktusvWS",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2016",
    link: "https://drive.google.com/open?id=198rISurdz4msprP994WPEjGf0LRIIcFS",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2016",
    link: "https://drive.google.com/open?id=1KSwTQCxfKBT4X0SO5lqJF4R1RH0Q9pa-",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2015",
    link: "https://drive.google.com/open?id=1Li1e85DS2k3xtR7kQZiBsfwcLoN7k3IU",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2015",
    link: "https://drive.google.com/open?id=1EH_hBlSJPxtn6HGhWXibTaNFa11_rSWE",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2014",
    link: "https://drive.google.com/open?id=1DPo4tRJ3qf5ttBEBH7SUVFX22VfLirGC",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2014",
    link: "https://drive.google.com/open?id=1VsU7aKKT1Nh98E78yrcH-Hhu3D1jK7uE",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2013",
    link: "https://drive.google.com/open?id=1HqB4hTAs1MAhYfyJvsH_3C09KdszUhYZ",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2013",
    link: "https://drive.google.com/open?id=1TOxOsQt1Y_VTIr78fVgT_tq1ovH1LQkg",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2012",
    link: "https://drive.google.com/open?id=1H8Zbb5HPgd4FmQ4NDEKbigondZ5m2oUJ",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2012",
    link: "https://drive.google.com/open?id=1Oy2opsbPrZUlI7xDp3Nst79aGWhGDOsP",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2011",
    link: "https://drive.google.com/open?id=1DzgTI3stzAoeB7S-J4t4KTBRlsFTtvmv",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2011",
    link: "https://drive.google.com/open?id=1gy9IZzLurcdu2gMZYhlqcOqJNXR0f0HG",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2010",
    link: "https://drive.google.com/open?id=1qrqB3VOrZ9UKaWnl1qpMl4QxsqkqjIT4",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2010",
    link: "https://drive.google.com/open?id=1QJKWQrJV-AOwwfH025KIKOurr96bJ0XT",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2009",
    link: "https://drive.google.com/open?id=10vMUMv99HiLvXVH_tedVuPIcPXg9qNKM",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2009",
    link: "https://drive.google.com/open?id=1FleO4arO4Yn86oAE45US6Jh6k1agU5Un",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2008",
    link: "https://drive.google.com/open?id=1VjugwBpDIFVVJAqVmh2rpINmuj8CjES2",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2008",
    link: "https://drive.google.com/open?id=1dRHhCaOa0arkN9ElPE4QFI9k0B2dEx8u",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2007",
    link: "https://drive.google.com/open?id=1UlsCV9fMb4VG_KJKW50Q69GBc8Lq0t68",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2007",
    link: "https://drive.google.com/open?id=1YuBG5KroWT3fPhkvj0XPd3MI9DgWnf0d",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2006",
    link: "https://drive.google.com/open?id=1t02vsbeNskVkIjo75tOOPxZ8VIuxCcrA",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2006",
    link: "https://drive.google.com/open?id=1nLaWnisfdssFtLPZqpyrcsdziYoCuYYi",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2005",
    link: "https://drive.google.com/open?id=1BnyYpB1FR3y2jjhOAy-hc9IDYqINLfnw",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2005",
    link: "https://drive.google.com/open?id=1U61E90vVhGKD-EzOJxWAXpEIBx3Q2ZAc",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2004",
    link: "https://drive.google.com/open?id=11Nz2XPaHxsK72AdcBa3if3LXB1Ft2lBI",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2004",
    link: "https://drive.google.com/open?id=1oiqecZovAIpbiEyVnWPImBxftIpdz5Ma",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2003",
    link: "https://drive.google.com/open?id=1eT_Vq5AIOlX0Ixio1q-3BXNadNps0Nre",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2003",
    link: "https://drive.google.com/open?id=1r4aODpz3kb9NbFcWzPwALcr6cd24rIB9",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2002",
    link: "https://drive.google.com/open?id=1M2pSvcKzA7OMFD9b47AZ6I24O44y-Hr2",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2002",
    link: "https://drive.google.com/open?id=1qL1jIbPNe5QmebBYQEu_sBRFW-gmefzc",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2001",
    link: "https://drive.google.com/open?id=1kDxyXVQcwhNw1WOw4cNF6EQ86_FNF_M1",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2001",
    link: "https://drive.google.com/open?id=1D97BibNm3tNTVzUDHFvUhajlZLqBGZ3T",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2000",
    link: "https://drive.google.com/open?id=10ICeC_yOJWala1d66PkWVUOEcpl3OTID",
  },
  {
    tipe: "MarkingScheme",
    year: "2019",
    link: "https://drive.google.com/open?id=19Hz9nzCHbfKMP_O-pplqUwceQUKUIwzx",
  },
  {
    tipe: "MarkingScheme",
    year: "2018",
    link: "https://drive.google.com/open?id=1Fr_wXVopr5UMKmom4CrTQ2CKjGGw-gqa",
  },
  {
    tipe: "MarkingScheme",
    year: "2017",
    link: "https://drive.google.com/open?id=1m2ewJ4_BIcLO47M9riSXkU6RoXXofc5b",
  },
  {
    tipe: "MarkingScheme",
    year: "2016",
    link: "https://drive.google.com/open?id=1QNeljSdkQ280WTqHwDHJb5KPo6xNH-Gx",
  },
  {
    tipe: "MarkingScheme",
    year: "2015",
    link: "https://drive.google.com/open?id=1Z9kI9a1SbJyVfBibAYJiSGfutHOu9uiH",
  },
  {
    tipe: "MarkingScheme",
    year: "2014",
    link: "https://drive.google.com/open?id=1wVCbbSKhehn8LuNzJdmMv_G188Df5Ctc",
  },
  {
    tipe: "MarkingScheme",
    year: "2013",
    link: "https://drive.google.com/open?id=1iABnTnlXeyrrG-e6xyTs1q28Q85R0XY5",
  },
  {
    tipe: "MarkingScheme",
    year: "2012",
    link: "https://drive.google.com/open?id=1wINd2Bt8h_ZRmWUhAinm7iyKq6M3grAH",
  },
  {
    tipe: "MarkingScheme",
    year: "2011",
    link: "https://drive.google.com/open?id=1yWSCGSe4C7Aj_J_C57_CTJ2apmbJKHE4",
  },
  {
    tipe: "MarkingScheme",
    year: "2010",
    link: "https://drive.google.com/open?id=16L6XQHsycP_vHEKbrfsb0PkOpEjFtaiQ",
  },
  {
    tipe: "MarkingScheme",
    year: "2009",
    link: "https://drive.google.com/open?id=15GUaFpGz1DhQK5bMF5C4DNoqeebDqO8I",
  },
  {
    tipe: "MarkingScheme",
    year: "2008",
    link: "https://drive.google.com/open?id=1_zXa_l2Z_b-L9INzLxOUNCiCU_kksJFc",
  },
  {
    tipe: "MarkingScheme",
    year: "2007",
    link: "https://drive.google.com/open?id=1zsagDl3rQB4xkyayiPFIQPOq6GZsQUXA",
  },
  {
    tipe: "MarkingScheme",
    year: "2006",
    link: "https://drive.google.com/open?id=1TQI0Mx2UNOeA_Dm4FkymDODp5vBjfmnR",
  },
  {
    tipe: "MarkingScheme",
    year: "2005",
    link: "https://drive.google.com/open?id=1GZPRTqTaZdl8SD9yxZX3wwR0EGuAEzsq",
  },
  {
    tipe: "MarkingScheme",
    year: "2004",
    link: "https://drive.google.com/open?id=1HANNxQu2SVa2TeYZw7gGjQS1w8GJNgYx",
  },
  {
    tipe: "MarkingScheme",
    year: "2003",
    link: "https://drive.google.com/open?id=1m2INf0TxkPaxfr7_LN8aarAYqcQOb_Vk",
  },
  {
    tipe: "MarkingScheme",
    year: "2002",
    link: "https://drive.google.com/open?id=1rHER6GVB4piv85U_XjOguzyO4YVAiCbI",
  },
  {
    tipe: "MarkingScheme",
    year: "2001",
    link: "https://drive.google.com/open?id=14sOq5kZ5oPffpVY44Nv9T-iFSIip0V3S",
  },
];
export const HLDCGPapers = [
  {
    tipe: "ExamPaper",
    year: "2019",
    paper: "A",
    link: "https://drive.google.com/open?id=1wkQJiPN5Xyk3FBxcTHkS3p9w2T_p0I2F",
  },
  {
    tipe: "ExamPaper",
    year: "2019",
    paper: "B",
    link: "https://drive.google.com/open?id=1WZOfKeaY6HEcroVGAnLfip62AGaaCuGT",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    paper: "A",
    link: "https://drive.google.com/open?id=1srVwRLRGQq6I_2Q-KX4Vxb3GW8kefQdR",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    paper: "B",
    link: "https://drive.google.com/open?id=1B1IEli_01k902_-WZYYdy4hp25lFMTKJ",
  },
  {
    tipe: "ExamPaper",
    year: "2017",
    paper: "A",
    link: "https://drive.google.com/open?id=1PjnX62IOALGoZWhrrCg3scSfpTUCPzC7",
  },
  {
    tipe: "ExamPaper",
    year: "2017",
    paper: "B",
    link: "https://drive.google.com/open?id=1Ayf59JXr-s0CKAtpGf_Yuv4Tgif2xEKz",
  },
  {
    tipe: "ExamPaper",
    year: "2016",
    paper: "A",
    link: "https://drive.google.com/open?id=1DSpum2Pzqfyn2WeEop9MbUHz9A_TI7Cj",
  },
  {
    tipe: "ExamPaper",
    year: "2016",
    paper: "B",
    link: "https://drive.google.com/open?id=12wdNdbezTUILvbQEoDJWG-aVuskoTpvO",
  },
  {
    tipe: "ExamPaper",
    year: "2015",
    paper: "A",
    link: "https://drive.google.com/open?id=1hFNANpJGg3orD4xu941qNEJg1uDEQ6EG",
  },
  {
    tipe: "ExamPaper",
    year: "2015",
    paper: "B",
    link: "https://drive.google.com/open?id=11B58nHadsP3oF-dbwOMnM8ZEWYVP5zVl",
  },
  {
    tipe: "ExamPaper",
    year: "2014",
    paper: "A",
    link: "https://drive.google.com/open?id=1-HCDnnrhnz19uyzJRpTmbKBcfhZXgxAt",
  },
  {
    tipe: "ExamPaper",
    year: "2014",
    paper: "B",
    link: "https://drive.google.com/open?id=1is5cSeXVDti0cf8mYSFvG7m7aXcHvMk4",
  },
  {
    tipe: "ExamPaper",
    year: "2013",
    paper: "A",
    link: "https://drive.google.com/open?id=1JDQWgCQuxeW6gxaIg3bBaEL5g1wQQQ28",
  },
  {
    tipe: "ExamPaper",
    year: "2013",
    paper: "B",
    link: "https://drive.google.com/open?id=1-Gr50TinwbeOul1-8WOfRXIxeHWnG7rQ",
  },
  {
    tipe: "ExamPaper",
    year: "2012",
    paper: "A",
    link: "https://drive.google.com/open?id=13a9hAcFW5YhHxOW3TDd_az184r0wuu5A",
  },
  {
    tipe: "ExamPaper",
    year: "2012",
    paper: "B",
    link: "https://drive.google.com/open?id=1zwGGXfK8L6LA6lut6th3JK9F6bjQteMz",
  },
  {
    tipe: "ExamPaper",
    year: "2011",
    paper: "A",
    link: "https://drive.google.com/open?id=1qWjJKMOesE3cWRy34Iujb5ODEBcaeFGd",
  },
  {
    tipe: "ExamPaper",
    year: "2011",
    paper: "B",
    link: "https://drive.google.com/open?id=1jAuzwqTPDTJPYglS5tU-TIeCaWHHRFlT",
  },
  {
    tipe: "ExamPaper",
    year: "2010",
    paper: "A",
    link: "https://drive.google.com/open?id=1LAqPkuw6ZVhWRbVMHj7LIg9rjsG1Ub_O",
  },
  {
    tipe: "ExamPaper",
    year: "2010",
    paper: "B",
    link: "https://drive.google.com/open?id=1NjUPLxmEBbeK0_ZQ-GpzJpOjFmXmuuPG",
  },
  {
    tipe: "ExamPaper",
    year: "2009",
    paper: "A",
    link: "https://drive.google.com/open?id=1GrCHEF7aKEPUZd4s2Z7N_QrYSi7MtzJT",
  },
  {
    tipe: "ExamPaper",
    year: "2009",
    paper: "B",
    link: "https://drive.google.com/open?id=11b4wI5JuWFRGw3Y2sLKoNxkuB2wc5YF0",
  },
  {
    tipe: "MarkingScheme",
    year: "2019",
    link: "https://drive.google.com/open?id=10JLAlHZuIY1UdBhzb9wV_zBapiGhtJE-",
  },
  {
    tipe: "MarkingScheme",
    year: "2018",
    link: "https://drive.google.com/open?id=1xs8GZDn5ZCP5OC763tb9t9PFUchpnu8W",
  },
  {
    tipe: "MarkingScheme",
    year: "2017",
    link: "https://drive.google.com/open?id=1fgHphrTlRT6V_JnLciBc-ys8kek_EbpC",
  },
  {
    tipe: "MarkingScheme",
    year: "2016",
    link: "https://drive.google.com/open?id=1vA2JYwr-H7MWpi8jj4ElMWTHRGmKkrgU",
  },
  {
    tipe: "MarkingScheme",
    year: "2015",
    link: "https://drive.google.com/open?id=1_5CyZ8WxZuQHxJoxsFwYX756TugDpxz7",
  },
  {
    tipe: "MarkingScheme",
    year: "2014",
    link: "https://drive.google.com/open?id=1Eh15W1lIaEE9tWcOmD3UrMescrTjTFtL",
  },
  {
    tipe: "MarkingScheme",
    year: "2013",
    link: "https://drive.google.com/open?id=1XY-xO3cJsepVju1fCpnZBmth17Ds0x0F",
  },
  {
    tipe: "MarkingScheme",
    year: "2012",
    link: "https://drive.google.com/open?id=1-oC8fbHzmR-pLXTQVEQcZqSIH-R71k-T",
  },
  {
    tipe: "MarkingScheme",
    year: "2011",
    link: "https://drive.google.com/open?id=1nB9XOx63GAD6lkKuSF5IHudJwvFUGGrx",
  },
  {
    tipe: "MarkingScheme",
    year: "2010",
    link: "https://drive.google.com/open?id=1FJaQZvzotiN12fFwCF1l3lrzLzq0e3YR",
  },
  {
    tipe: "MarkingScheme",
    year: "2009",
    link: "https://drive.google.com/open?id=17IS7_uY3liOUjBzBHM4e4cA1r01Ncsa1",
  },
];
export const HLPhysicsPapers = [
  {
    tipe: "ExamPaper",
    year: "2019",
    link: "https://drive.google.com/open?id=1fARaqZqUCLWKccMqDp2gKeJPYyI1QCx7",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    link: "https://drive.google.com/open?id=1HUAw3H0i_2mv-VVXOL7g6Zx6Dv5iIbl2",
  },
  {
    tipe: "ExamPaper",
    year: "2017",
    link: "https://drive.google.com/open?id=1A8k34TMFm5dR2D4h795_uibXR0e2kb7t",
  },
  {
    tipe: "ExamPaper",
    year: "2016",
    link: "https://drive.google.com/open?id=1aZXqc42myao92r2gy4495uWsY3wRBXYG",
  },
  {
    tipe: "ExamPaper",
    year: "2015",
    link: "https://drive.google.com/open?id=1GBKgfVpPqvJxwgujbbTtYZXCzRyT0Vva",
  },
  {
    tipe: "ExamPaper",
    year: "2014",
    link: "https://drive.google.com/open?id=1ngrDppnwkcri-moM_5X_kUfS8Dnz4MxM",
  },
  {
    tipe: "ExamPaper",
    year: "2013",
    link: "https://drive.google.com/open?id=1gZ2FJxrsYm3up8acr8Npg-u02_6n9FWO",
  },
  {
    tipe: "ExamPaper",
    year: "2012",
    link: "https://drive.google.com/open?id=1qGf2SD7JBMTBvvt6FW4pJTJz7IveG2Jc",
  },
  {
    tipe: "ExamPaper",
    year: "2011",
    link: "https://drive.google.com/open?id=1-jl-1Rfd44EIUk1Tgj3VYd6WtD1cmlko",
  },
  {
    tipe: "ExamPaper",
    year: "2010",
    link: "https://drive.google.com/open?id=1aoSjG3yVhVTwrjTi2Qki7DLddICQEixm",
  },
  {
    tipe: "ExamPaper",
    year: "2009",
    link: "https://drive.google.com/open?id=17bSAd3jdG7wKGiDtEKPcOmP7vUj3IEE_",
  },
  {
    tipe: "ExamPaper",
    year: "2008",
    link: "https://drive.google.com/open?id=1vzxeN981Dc_m7jL-SQWSzaRVq0o637Hk",
  },
  {
    tipe: "ExamPaper",
    year: "2007",
    link: "https://drive.google.com/open?id=17IiY592g_T2w4KlnCQvfuTzejTpzRBd6",
  },
  {
    tipe: "ExamPaper",
    year: "2006",
    link: "https://drive.google.com/open?id=1FeiW9zQJ96WTKXkJZRzBtaoACkJt8mTw",
  },
  {
    tipe: "ExamPaper",
    year: "2005",
    link: "https://drive.google.com/open?id=1GW0YCqVzyx3OhHN1OI0I5F1LqI1vPm4D",
  },
  {
    tipe: "ExamPaper",
    year: "2004",
    link: "https://drive.google.com/open?id=1VGTEtTvSDubyyqEF34hyR0p7xhuf96Ag",
  },
  {
    tipe: "ExamPaper",
    year: "2003",
    link: "https://drive.google.com/open?id=122k5pyZ0fFS5gJbKsOlcpfdzhXEr5I28",
  },
  {
    tipe: "ExamPaper",
    year: "2002",
    link: "https://drive.google.com/open?id=1PgtAcBcD5sQkbu79h4wpFGeXsoUNUHGb",
  },
  {
    tipe: "ExamPaper",
    year: "2001",
    link: "https://drive.google.com/open?id=14T8N9HRlE7TYHqrj2Lbrof0fMFX14Mxo",
  },
  {
    tipe: "ExamPaper",
    year: "2000",
    link: "https://drive.google.com/open?id=1ytFVjfELP2hed8EuhPhf8UpbFDhXETst",
  },
  {
    tipe: "MarkingScheme",
    year: "2019",
    link: "https://drive.google.com/open?id=1V5LRovKqRCJeZ7aBRJGfM5pwR6laMRiz",
  },
  {
    tipe: "MarkingScheme",
    year: "2018",
    link: "https://drive.google.com/open?id=1ZjeJNnCUHKS7YwtWX7MP3fcpx40zcd8y",
  },
  {
    tipe: "MarkingScheme",
    year: "2017",
    link: "https://drive.google.com/open?id=1D_rhAenUrGnXD9YtG1DmretUzJ8w8X23",
  },
  {
    tipe: "MarkingScheme",
    year: "2016",
    link: "https://drive.google.com/open?id=1CAYkB0SzCepfLBXnvl0Wh7C1LQ9hEvBi",
  },
  {
    tipe: "MarkingScheme",
    year: "2015",
    link: "https://drive.google.com/open?id=1BQFl8Fl69piZd-o0iyUgRw6c-KJ4O8xc",
  },
  {
    tipe: "MarkingScheme",
    year: "2014",
    link: "https://drive.google.com/open?id=1tnhsWT9s4cF-s6fOMucA1-n7H2RMPUYy",
  },
  {
    tipe: "MarkingScheme",
    year: "2013",
    link: "https://drive.google.com/open?id=1NSf2vQEsoMVtW_W72uUUecs0HRB5kj2x",
  },
  {
    tipe: "MarkingScheme",
    year: "2012",
    link: "https://drive.google.com/open?id=1uwYFK6gQ-hKYzTB9t13sSxVY3vouVcB2",
  },
  {
    tipe: "MarkingScheme",
    year: "2011",
    link: "https://drive.google.com/open?id=1YpkCSQPBqCb2fQTuX9SZeYVidd8Qm_eI",
  },
  {
    tipe: "MarkingScheme",
    year: "2010",
    link: "https://drive.google.com/open?id=1wlYQkmROUEwixSu4pt14l04WTCdwWR0Y",
  },
  {
    tipe: "MarkingScheme",
    year: "2009",
    link: "https://drive.google.com/open?id=1Q7j6lud4pyhGWPUV5ZjrS9d8sAzy03xI",
  },
  {
    tipe: "MarkingScheme",
    year: "2008",
    link: "https://drive.google.com/open?id=1BSUJlGTzHWjUvw4DRg5OkT5APLYOyD1o",
  },
  {
    tipe: "MarkingScheme",
    year: "2007",
    link: "https://drive.google.com/open?id=14YJPkp14KWnf0OJSN4d1AlqobnDW2PUW",
  },
  {
    tipe: "MarkingScheme",
    year: "2006",
    link: "https://drive.google.com/open?id=19KzqOdkiFLIfkVVceeCGBvxcX1-5xMZF",
  },
  {
    tipe: "MarkingScheme",
    year: "2005",
    link: "https://drive.google.com/open?id=1hnOAQo3B0oIdibWT5_D0bS1KSwX7DtjI",
  },
  {
    tipe: "MarkingScheme",
    year: "2004",
    link: "https://drive.google.com/open?id=1fMwl8FJybUw2Y4Kq71X540ZDVWvR-Xwe",
  },
  {
    tipe: "MarkingScheme",
    year: "2003",
    link: "https://drive.google.com/open?id=1dbz2nQ1ZSycOox8okw9OgcTlQck5v4d2",
  },
  {
    tipe: "MarkingScheme",
    year: "2002",
    link: "https://drive.google.com/open?id=1--Z5En_9IFKjMThGlVOqsh-rzQlhIhWh",
  },
  {
    tipe: "MarkingScheme",
    year: "2001",
    link: "https://drive.google.com/open?id=124QQgHncyNEmHKuSRdcTF8lSeI1wz6tK",
  },
];
export const HLAppliedMathsPapers = [
  {
    tipe: "ExamPaper",
    year: "2019",
    link: "https://drive.google.com/open?id=18OalbjR3JV9ShtAQ9_oISxzNbTirr7XO",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    link: "https://drive.google.com/open?id=1TRWWlyQvwZWHQDCj0lKNvjutdVjoMzkp",
  },
  {
    tipe: "ExamPaper",
    year: "2017",
    link: "https://drive.google.com/open?id=1kpn9b-SdoL5xjsrfy4S_-6fhXN77EMvg",
  },
  {
    tipe: "ExamPaper",
    year: "2016",
    link: "https://drive.google.com/open?id=1QhEUQBwsmtaX8DG2VKQ57b4aKIquayFD",
  },
  {
    tipe: "ExamPaper",
    year: "2015",
    link: "https://drive.google.com/open?id=1S9sAIOGg1eKEzB6vw0pHousuYOTH_lYH",
  },
  {
    tipe: "ExamPaper",
    year: "2014",
    link: "https://drive.google.com/open?id=1bYR-B85DiVS0pMQbtviH0ERJOxjWnEDd",
  },
  {
    tipe: "ExamPaper",
    year: "2013",
    link: "https://drive.google.com/open?id=1wF0LL4FnM8QMIBC-bGmwlmBh7PVvffGw",
  },
  {
    tipe: "ExamPaper",
    year: "2012",
    link: "https://drive.google.com/open?id=1cU3_A9Y5CmX2gGZ_M0rORiQdINuPFSiy",
  },
  {
    tipe: "ExamPaper",
    year: "2011",
    link: "https://drive.google.com/open?id=16h7Nd-v1XgmljvYSrT6T5OTGkJSgK5qY",
  },
  {
    tipe: "ExamPaper",
    year: "2010",
    link: "https://drive.google.com/open?id=1LW5YSeeQfcOjcZSJ7jhArDFdm1C1xeWQ",
  },
  {
    tipe: "ExamPaper",
    year: "2009",
    link: "https://drive.google.com/open?id=1o11M8t6Z3-ZiQbUTxTD-RTra_1r0oTXT",
  },
  {
    tipe: "ExamPaper",
    year: "2008",
    link: "https://drive.google.com/open?id=1LC1xXWfYFEKSpL1Gy9NRgEFBQxXns0i4",
  },
  {
    tipe: "ExamPaper",
    year: "2007",
    link: "https://drive.google.com/open?id=1RNuJDDDYXCyClHQ_uKT5BAJRpqylFjkz",
  },
  {
    tipe: "ExamPaper",
    year: "2006",
    link: "https://drive.google.com/open?id=1GmdzZN8FQ44s5YO2x0e2Z_tjuSGUaTSw",
  },
  {
    tipe: "ExamPaper",
    year: "2005",
    link: "https://drive.google.com/open?id=1XAKWd89MWtU3RQ5IrUU-jJeHlwj95Bnx",
  },
  {
    tipe: "ExamPaper",
    year: "2004",
    link: "https://drive.google.com/open?id=1kEN4qvQO8uE5wtmYRtdCv3Hr8-N3Nrbs",
  },
  {
    tipe: "ExamPaper",
    year: "2003",
    link: "https://drive.google.com/open?id=1ono2UXJsvr154ZpOMKZyRC0D5DZ2M-Bm",
  },
  {
    tipe: "ExamPaper",
    year: "2002",
    link: "https://drive.google.com/open?id=1vdsO_5trndSHiD2IaasIi890acCNVeik",
  },
  {
    tipe: "ExamPaper",
    year: "2001",
    link: "https://drive.google.com/open?id=1fSgXcOCbGt99WMPtkSc-GPfTceglopXv",
  },
  {
    tipe: "ExamPaper",
    year: "2000",
    link: "https://drive.google.com/open?id=1-XVmnM0gTOUQjWwbBQHaGpy7Ep_O-mBB",
  },
  {
    tipe: "ExamPaper",
    year: "1999",
    link: "https://drive.google.com/open?id=10AO4fAn5AIRcx86RDyjQStEgUukRpgYd",
  },
  {
    tipe: "ExamPaper",
    year: "1998",
    link: "https://drive.google.com/open?id=1wcD_k6mLGpptnr9fuc3zABk61nnmCuFU",
  },
  {
    tipe: "ExamPaper",
    year: "1997",
    link: "https://drive.google.com/open?id=1D4NbHe64YGKxyvbgM8C6gn_xcvncP-sd",
  },
  {
    tipe: "ExamPaper",
    year: "1996",
    link: "https://drive.google.com/open?id=136klzqJ0IEzzCVCHsVwXeZtlM81-NxDv",
  },
  {
    tipe: "MarkingScheme",
    year: "2019",
    link: "https://drive.google.com/open?id=18KB0l8KpNufjrluQnlA9V5ayngyZ3uPy",
  },
  {
    tipe: "MarkingScheme",
    year: "2018",
    link: "https://drive.google.com/open?id=1dcULeEoT0a0DemDfkJqYswPq_lwfFZkR",
  },
  {
    tipe: "MarkingScheme",
    year: "2017",
    link: "https://drive.google.com/open?id=1TvlMxMpKcXvz1mSkHuQ_Ij_09lmSrhSx",
  },
  {
    tipe: "MarkingScheme",
    year: "2016",
    link: "https://drive.google.com/open?id=1Yjg-QrU7c8NsLETQiTdtRCjCbLFPLB1w",
  },
  {
    tipe: "MarkingScheme",
    year: "2015",
    link: "https://drive.google.com/open?id=1HWvLhZtLmxcIP_kkzr88Ljw5X3wbGWse",
  },
  {
    tipe: "MarkingScheme",
    year: "2014",
    link: "https://drive.google.com/open?id=1urQzRPVAEFBCxXUChuTBQPOyOFUd2zYd",
  },
  {
    tipe: "MarkingScheme",
    year: "2013",
    link: "https://drive.google.com/open?id=1W_xmlEY8qqIeGadeT0s6_1M_sA0kl5VG",
  },
  {
    tipe: "MarkingScheme",
    year: "2012",
    link: "https://drive.google.com/open?id=1o0C-K1OacQQYiMO36STFkn8l6YVhlkVv",
  },
  {
    tipe: "MarkingScheme",
    year: "2011",
    link: "https://drive.google.com/open?id=1Ij6tWqmPRjAd-2o4lXUdEogNk_qGrrAK",
  },
  {
    tipe: "MarkingScheme",
    year: "2010",
    link: "https://drive.google.com/open?id=1JH5m2anpflCJXXfBhyVxS6bVQKQOxv8w",
  },
  {
    tipe: "MarkingScheme",
    year: "2009",
    link: "https://drive.google.com/open?id=1RGP3LrCqA6yTVXs1AwYQfrIkz9QB0Kjm",
  },
  {
    tipe: "MarkingScheme",
    year: "2008",
    link: "https://drive.google.com/open?id=1at91tqXo-8t7qADThV2Adrd8KTIFS88L",
  },
  {
    tipe: "MarkingScheme",
    year: "2007",
    link: "https://drive.google.com/open?id=1QhvRUotZFM34pDTOFOzxDFoaKBmZSXbd",
  },
  {
    tipe: "MarkingScheme",
    year: "2006",
    link: "https://drive.google.com/open?id=1-Tli7wfllCZrmq0vBPMSaaydfkzRRzXP",
  },
  {
    tipe: "MarkingScheme",
    year: "2005",
    link: "https://drive.google.com/open?id=1LaaANcd-INzl2KgZgu51DCMpAhGXH_v4",
  },
  {
    tipe: "MarkingScheme",
    year: "2004",
    link: "https://drive.google.com/open?id=1DShteCz0kGZSTxolf7HlWFDAKyOKRGli",
  },
  {
    tipe: "MarkingScheme",
    year: "2003",
    link: "https://drive.google.com/open?id=1huuTmRBVtjYAk2WRg-KnZHj5SBCtTRwp",
  },
  {
    tipe: "MarkingScheme",
    year: "2002",
    link: "https://drive.google.com/open?id=1zd749H3nyALXKBpEq5hb66fhT3gxdvb6",
  },
  {
    tipe: "MarkingScheme",
    year: "2001",
    link: "https://drive.google.com/open?id=1YArure4t_LHGYKc5g4RZnPxaGIB1WorE",
  },
];
export const OLEnglishPapers = [
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2019",
    link: "https://drive.google.com/open?id=1kPRhOhqOA50UhnBCypqFMvy0Fd2tXn14",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2019",
    link: "https://drive.google.com/open?id=1L1ZPb_2FwunT6o4aLE4exzA6wp2V3KeC",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2018",
    link: "https://drive.google.com/open?id=1dX_nHDVcbepolXOR3C9TxYMjGy-TD79N",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2018",
    link: "https://drive.google.com/open?id=1MLiuZIfOSM_8guAEbbIZfIY9597YhqjF",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2017",
    link: "https://drive.google.com/open?id=1cr4n1PnyS0GUrxNV_gnvjR3Nomd9_-zR",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2017",
    link: "https://drive.google.com/open?id=1_6R1aQZRuMcusrpdSy_9ADQ1NefK1o07",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2016",
    link: "https://drive.google.com/open?id=1YI7EVWpKN7lOBBQz9qnuGXT-xIJA1bAd",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2016",
    link: "https://drive.google.com/open?id=13g58j-7Ku3Tuu05rZkYOrEr6Iiub3so9",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2015",
    link: "https://drive.google.com/open?id=1vNHVlVQ7PtYgu2oNQPSYi706-nSU9v-a",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2015",
    link: "https://drive.google.com/open?id=1bzkKbE7h78qxWLnVK0kCvR0xW78_spHv",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2014",
    link: "https://drive.google.com/open?id=1mQCw-UQ-1eaNDf6RGtWPzPi-J_DwOofl",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2014",
    link: "https://drive.google.com/open?id=16GyYT07eSDA8tgfZDn0iwDDDzcwjXIV3",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2013",
    link: "https://drive.google.com/open?id=1VJqnoMUPA626FYuefnmzgf23F4EuMEqq",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2013",
    link: "https://drive.google.com/open?id=1S9naQW1eE0_YG9VrF-MxGmYzKir8mTyT",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2012",
    link: "https://drive.google.com/open?id=1NfIB2csT84hVSJPJFPOTY1mA6-GBeMlW",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2012",
    link: "https://drive.google.com/open?id=1drcoT8-87oOD_MkkF7syVZJbNfZgSLuQ",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2011",
    link: "https://drive.google.com/open?id=1eMli3ewg_YOsQ4N6tHvx_w6c9n9J1CxE",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2011",
    link: "https://drive.google.com/open?id=1YEku-g3oxzOrIqRnID0hdU0L-QOxxj5g",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2010",
    link: "https://drive.google.com/open?id=1DJJDISGu9OPLYei1EPaYw8juStnh8sVX",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2010",
    link: "https://drive.google.com/open?id=1Ap0tJmT20353Cfy6Ae9tIX-9t7FRpvei",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2009",
    link: "https://drive.google.com/open?id=1f0M4iVVDwcq-6jEAOvk94FQcIvum1j18",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2009",
    link: "https://drive.google.com/open?id=1hhmBPcuUuWY73q31pav4jYKm2D6snkRL",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2008",
    link: "https://drive.google.com/open?id=11fMUnhX8ubuTN8BhUoKkkqSFhIFOpJ5v",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2008",
    link: "https://drive.google.com/open?id=1BmcYMqkQYsP7e6khPmCweVwVyRyVfIuP",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2007",
    link: "https://drive.google.com/open?id=1WsGnSpd6SpMoP8mrnfEVhuLx8Ajq326K",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2007",
    link: "https://drive.google.com/open?id=1BI_ZPXx5BI7Q1vJTRkyH_G6Z71vgp5ec",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2006",
    link: "https://drive.google.com/open?id=1Jlixc4_xOyo-I63R4_USS9XUDrtAn9UD",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2006",
    link: "https://drive.google.com/open?id=1f2KXH4O30Nx7MT8TyElX19p8TfgoRNx3",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2005",
    link: "https://drive.google.com/open?id=1iyiuw-kCb4cvh-DZPOhMF87VYH8X5vqr",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2005",
    link: "https://drive.google.com/open?id=1CQvx9IP8NEDpknaRHNSxcjNPw4mjWWiJ",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2004",
    link: "https://drive.google.com/open?id=1tQe4Lue8XjvWpW2nw-GJMFH1uqDkXyua",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2004",
    link: "https://drive.google.com/open?id=1BqaVoWeLxJZ68HVXiMiXzfcV2ee8eZBC",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2003",
    link: "https://drive.google.com/open?id=1ZofmYwYPCfHWgAn7wyyEkcRjAfc0BZnO",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2003",
    link: "https://drive.google.com/open?id=1P8Mt27irZUw3bbDzc-L5TOBbyxM8zGNm",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2002",
    link: "https://drive.google.com/open?id=1YgwHyRE0UbFYc_9MU7L3HEJFlDN9Kn6b",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2002",
    link: "https://drive.google.com/open?id=1BdQfgketCMEHA6Cz7lnmtqEH9TXqTmrK",
  },
  {
    tipe: "ExamPaper",
    paper: "One",
    year: "2001",
    link: "https://drive.google.com/open?id=1a5X9drea2KA4e34-u4SAXjPBvmeBDX9x",
  },
  {
    tipe: "ExamPaper",
    paper: "Two",
    year: "2001",
    link: "https://drive.google.com/open?id=13A9d6af-v5bnPHewbzIJi_MFLWLkN5pK",
  },
  {
    tipe: "MarkingScheme",
    year: "2019",
    link: "https://drive.google.com/open?id=1Dmgrn1e2stpM5K9-tUFCTG6OJy91kqfz",
  },
  {
    tipe: "MarkingScheme",
    year: "2018",
    link: "https://drive.google.com/open?id=14nx4U8kYT7e3V68B2hoqBdLDYZz6i_tc",
  },
  {
    tipe: "MarkingScheme",
    year: "2017",
    link: "https://drive.google.com/open?id=1d7I-LLu4PuZl8oZFKA53VrGID7YjgAW9",
  },
  {
    tipe: "MarkingScheme",
    year: "2016",
    link: "https://drive.google.com/open?id=1Da1_VTwcikxRrHR7QqEtvr-smgnDC17u",
  },
  {
    tipe: "MarkingScheme",
    year: "2015",
    link: "https://drive.google.com/open?id=1V_ZZz4sKFgEcsvZfl8yw1896K2MJNkfv",
  },
  {
    tipe: "MarkingScheme",
    year: "2014",
    link: "https://drive.google.com/open?id=1GGfTcaQHRXLw63LBFMR0saIFrrXJO9lx",
  },
  {
    tipe: "MarkingScheme",
    year: "2013",
    link: "https://drive.google.com/open?id=10ydIv_auBUfKeeFG27CjNbiDoUzJLyCr",
  },
  {
    tipe: "MarkingScheme",
    year: "2012",
    link: "https://drive.google.com/open?id=1Kr_x9PXeqCj70_G7pDqFKHNp7GXORLi4",
  },
  {
    tipe: "MarkingScheme",
    year: "2011",
    link: "https://drive.google.com/open?id=1vFvvPxdAN5RakWlc7lO79lrgAYnuXxdp",
  },
  {
    tipe: "MarkingScheme",
    year: "2010",
    link: "https://drive.google.com/open?id=10Y7pyIHaN-tOudP1fgIp8xohL4_ToIZC",
  },
  {
    tipe: "MarkingScheme",
    year: "2009",
    link: "https://drive.google.com/open?id=1ugQA4Wni2IvBKrP176BOyqaryHxzzZaY",
  },
  {
    tipe: "MarkingScheme",
    year: "2008",
    link: "https://drive.google.com/open?id=1U28vh0ZGtNw180-bSt-i6yg8UGVk07Lz",
  },
  {
    tipe: "MarkingScheme",
    year: "2007",
    link: "https://drive.google.com/open?id=1VwTQrMR3GiRWTGEG3GKrdWZxG_QxZqyM",
  },
  {
    tipe: "MarkingScheme",
    year: "2006",
    link: "https://drive.google.com/open?id=1u4O3bSM1g3FCuR21JtZcCUf6F4Kj4A4e",
  },
  {
    tipe: "MarkingScheme",
    year: "2005",
    link: "https://drive.google.com/open?id=1vx5JP5tgZ011cTVsobCnDerzUVGTRQS9",
  },
  {
    tipe: "MarkingScheme",
    year: "2004",
    link: "https://drive.google.com/open?id=19hfBmLhgQFEQRUGhyhqG4LOoLdankAnN",
  },
  {
    tipe: "MarkingScheme",
    year: "2003",
    link: "https://drive.google.com/open?id=19nse7LG1biOzflo83iHLlX35hhL_znha",
  },
  {
    tipe: "MarkingScheme",
    year: "2002",
    link: "https://drive.google.com/open?id=1lciKtMFG5knNFkatGwjjsq8kvA6G3mjn",
  },
  {
    tipe: "MarkingScheme",
    year: "2001",
    link: "https://drive.google.com/open?id=1fgFxB9ozI4jsnZckfUou5ByONHORQm08",
  },
];
export const OLIrishPapers = [
];
export const OLMathsPapers = [
];