export const Papers = [
  {
    tipe: "ExamPaper",
    year: "2019",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1OKE3hwhuJCAZsHUL8M0sw00YHyM9Fz39",
  },
  {
    tipe: "ExamPaper",
    year: "2019",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=11tPHhko7Zju4U30SQSIApgjWNn8Mix6J",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1qJQwEBLZdhHfAR0gncERUMuxs-ZQV9F1",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1GXnSnpwFUSXy_BOi3xjcdVuhH6xAaHRi",
  },
  {
    tipe: "ExamPaper",
    year: "2017",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1KcClmGcQouyvIXKyIGow12h-LOK4aZik",
  },
  {
    tipe: "ExamPaper",
    year: "2017",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1ilwLBgKbHUljVsajTLSVebpb0z6Qyg6z",
  },
  {
    tipe: "ExamPaper",
    year: "2016",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1eljAD5CpIZlLTgiB9BRFc2-WbBrj_Vow",
  },
  {
    tipe: "ExamPaper",
    year: "2016",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1pWtUhMvKS8_rf086QzGm5ocvfjn54SLG",
  },
  {
    tipe: "ExamPaper",
    year: "2015",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1AS8DnAszP3Kp2FI4-Rxe5f5XQHFKjFMn",
  },
  {
    tipe: "ExamPaper",
    year: "2015",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1WVcsRYhrn3fkUNBL8bWERgdEcVaioBHq",
  },
  {
    tipe: "ExamPaper",
    year: "2014",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1ryiYG4Dn_Eg4xFwb9Adi8_gDXFIeccpY",
  },
  {
    tipe: "ExamPaper",
    year: "2014",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1R08nZ4e86h6K2AnlksYzJvCdqkvPv7o_",
  },
  {
    tipe: "ExamPaper",
    year: "2013",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1ggdENITr5VjwtwTB1SM6Ee_V0WWXajAG",
  },
  {
    tipe: "ExamPaper",
    year: "2013",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1hJiCSkhOdaq9SlKovlN0lHTo_wJ7tjHT",
  },
  {
    tipe: "ExamPaper",
    year: "2012",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1yLHZzdY2fvAmMqTgxn90QEgU559xThX-",
  },
  {
    tipe: "ExamPaper",
    year: "2012",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1u4vrRgO8iGuR7rTZDC-kuwAeEIYmedqB",
  },
  {
    tipe: "ExamPaper",
    year: "2011",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1EcI3cJkjsqZXxCBDjOhoabfu_YDwv6_7",
  },
  {
    tipe: "ExamPaper",
    year: "2011",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1f_GnH-KrFLTmygjwecf5jYxlVzN4mViN",
  },
  {
    tipe: "ExamPaper",
    year: "2010",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1vNvDq1kRJMFuxica59FTxlOM5vRSMtQc",
  },
  {
    tipe: "ExamPaper",
    year: "2010",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=10lqz-Ch40B4HUcsGIy9bXjtlsy7jUg0A",
  },
  {
    tipe: "ExamPaper",
    year: "2009",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=13RwygqounJiRp9KlqYIN8hYY2b8Mmj_a",
  },
  {
    tipe: "ExamPaper",
    year: "2009",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=17hWCR0oz1LbkxCASdOIduj29_5pxNhEY",
  },
  {
    tipe: "ExamPaper",
    year: "2008",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1gADmICMI9voe3Yxdhix3n-X-m9Xeb0Je",
  },
  {
    tipe: "ExamPaper",
    year: "2008",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1i-frtVcqBB0nf176JqsL03zL0NzfrMQs",
  },
  {
    tipe: "ExamPaper",
    year: "2007",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1EGZSM2f5YjUgvaEbnqz0zj0k_dwMqb9j",
  },
  {
    tipe: "ExamPaper",
    year: "2007",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1c4pIr34s89oaBVxWrcV0sHrTbLe3qMvY",
  },
  {
    tipe: "ExamPaper",
    year: "2006",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1Vv7--ek-nYPJSPLXEVsRapwzKGGoy5-r",
  },
  {
    tipe: "ExamPaper",
    year: "2006",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=10avQcRp3lPflYYn1TNpUfiC4IVlJGXv9",
  },
  {
    tipe: "ExamPaper",
    year: "2005",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1ZGAjNLCd1HcgKbPfrN_jm38LVqGm45Ai",
  },
  {
    tipe: "ExamPaper",
    year: "2005",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=17LtXXHr-1onraeUrnw_P2UdB8pgQVhi2",
  },
  {
    tipe: "ExamPaper",
    year: "2004",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1rp-QVJmkDTqoOGtLtaXTVmK5ZSpOvz2h",
  },
  {
    tipe: "ExamPaper",
    year: "2004",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1P9e4Jj7K8M0DZACIEQLKDTMXjoy-q_Zl",
  },
  {
    tipe: "ExamPaper",
    year: "2003",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1k1jDqvt2-fgpu1wEEHlQXQ6TOV50NiCn",
  },
  {
    tipe: "ExamPaper",
    year: "2003",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1I8lu9F16ZKwrP0u0DANcZWuQ4Byr5yUo",
  },
  {
    tipe: "ExamPaper",
    year: "2002",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1mVSZGBpcA1GxPi2479lNz-1lRu7eltSV",
  },
  {
    tipe: "ExamPaper",
    year: "2002",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1uV0BqsOH6K9YsSV286eNBI902jQ0rXGD",
  },
  {
    tipe: "ExamPaper",
    year: "2001",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1grdZNqtziqUy0rXKcweP7valH21L5S4X",
  },
  {
    tipe: "ExamPaper",
    year: "2001",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1lrg-pBWucReOew73QGzTpI5tiGMni-LU",
  },
  {
    tipe: "ExamPaper",
    year: "2000",
    subject: "Maths",
    paper: "",
    link: "https://drive.google.com/open?id=1jssR1kXDWCgPPUyotRG73Zxoo86bBc8y",
  },
];