export const Papers = [
  {
    tipe: "ExamPaper",
    year: "2019",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1OKE3hwhuJCAZsHUL8M0sw00YHyM9Fz39",
  },
  {
    tipe: "ExamPaper",
    year: "2019",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=11tPHhko7Zju4U30SQSIApgjWNn8Mix6J",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1qJQwEBLZdhHfAR0gncERUMuxs-ZQV9F1",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "Two",
    link: "https://drive.google.com/open?id=1GXnSnpwFUSXy_BOi3xjcdVuhH6xAaHRi",
  },
  {
    tipe: "ExamPaper",
    year: "2017",
    subject: "Maths",
    paper: "One",
    link: "https://drive.google.com/open?id=1KcClmGcQouyvIXKyIGow12h-LOK4aZik",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
  {
    tipe: "ExamPaper",
    year: "2018",
    subject: "Maths",
    paper: "One",
    link: "",
  },
];